config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  

  # libraries
  root 'libraries#index'
  
  get '/Libraries', to: 'libraries#index', as: 'libraries'
  post '/Libraries', to: 'libraries#create', as: 'add_book'
  delete '/Libraries/:id', to: 'libraries#destroy', as: 'library_delete'
  get '/Libraries/new', to: 'libraries#new', as: 'new_library'
  patch '/libraries/:id', to: 'libraries#update'
  post '/libraries/:id/borrow', to: 'libraries#borrow', as: 'borrow_book'
  get '/libraries/:id', to: 'libraries#show', as: "show_book"
  get '/libraries/:id/edit', to: 'libraries#edit', as: 'edit_library'

  # users

  get '/users', to: 'users#index', as: 'users'
  post '/users', to: 'users#create'
  get '/users/signin', to: 'users#signin', as: 'signin'
  post '/users/login', to: 'users#login', as: 'login'
  get '/users/new', to: 'users#new', as: 'new_user'
  get '/users/:id', to: 'users#edit', as: 'user'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update'
  put '/users/:id', to: 'users#update'
  delete '/users/:id', to: 'users#destroy'

  get '/waitinglist', to: 'waitinglists#index', as: 'waitinglists'
  post '/waitinglist/:id', to: 'waitinglists#new'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
    validates :name, :email, :password, :access, presence: true
    attribute :name, default: ''
    attribute :email, default: ''
    attribute :access, default: 'basic'
    has_many :libraries

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # /Get signin
  def signin

  end

  def login
    user = User.exists?(email: user_params[:email])
    respond_to do |format|
      if user
        format.html { redirect_to root_path, notice: "You have successfully Logged in.", :status => 'Succcessful' }
      else
        format.html { redirect_to @user, notice: "User does not exist reegister please.",  :status => 'Unsucccessful' }
      end
    end
  end


  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    if user_params[:admin] == 1 
      user_params[:admin] == 'true'
    elsif user_params[:librarian] == 1
      user_params[:librarian] == 'true'
    end
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name, :email, :password, :access, :role, :admin, :librarian)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :role %>
    <%= form.text_field :role %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_form2.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :role %>
    <%= form.text_field :role %>
  </div>

  <div class="field">
    <%= form.label :admin %>
    <%= form.check_box :admin %>
  </div>

  <div class="field">
    <%= form.label :librarian %>
    <%= form.check_box :librarian %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form2', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th>Email</th>
      <th></th>
      <th>Access</th>
      <th></th>
      <th>Role</th>
      <th></th>
      <th>Admin Access</th>
      <th>Library Access</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td></td>
        <td><%= user.email %></td>
        <td></td>
        <td><%= user.access %></td>
        <td></td>
        <td><%= user.role %></td>
        <td></td>
        <td><%= user.admin %></td>
        <td><%= user.librarian %></td>
        <td></td>
        <td><%= user.role %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/new.html.erb
<h1>Register</h1>

<%= render 'form', user: @user %>

<%= link_to 'Already have an account', signin_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Access:</strong>
  <%= @user.access %>
</p>

<p>
  <strong>Role:</strong>
  <%= @user.role %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>

app/views/users/signin.html.erb
<h1>Sign In</h1>
<p>If admin/librarian sign in with the admin/librarian details</p>
<p>For admin or super admiin access ask a super admin to change your status to admin</p>
<%= form_with(model: @users) do |form| %>
  
    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email %>
    </div>
  
    <div class="field">
      <%= form.label :password %>
      <%= form.text_field :password %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

<%= link_to 'Register', new_user_path %>