config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  

  # libraries
  root 'libraries#index'
  
  get '/Libraries', to: 'libraries#index', as: 'libraries'
  post '/Libraries', to: 'libraries#create', as: 'add_book'
  delete '/Libraries/:id', to: 'libraries#destroy', as: 'library_delete'
  get '/Libraries/new', to: 'libraries#new', as: 'new_library'
  patch '/libraries/:id', to: 'libraries#update'
  post '/libraries/:id/borrow', to: 'libraries#borrow', as: 'borrow_book'
  get '/libraries/:id', to: 'libraries#show', as: "show_book"
  get '/libraries/:id/edit', to: 'libraries#edit', as: 'edit_library'

  # users

  get '/users', to: 'users#index', as: 'users'
  post '/users', to: 'users#create'
  get '/users/signin', to: 'users#signin', as: 'signin'
  post '/users/login', to: 'users#login', as: 'login'
  get '/users/new', to: 'users#new', as: 'new_user'
  get '/users/:id', to: 'users#edit', as: 'user'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update'
  put '/users/:id', to: 'users#update'
  delete '/users/:id', to: 'users#destroy'

  get '/waitinglist', to: 'waitinglists#index', as: 'waitinglists'
  post '/waitinglist/:id', to: 'waitinglists#new'
end

app/models/library.rb
class Library < ApplicationRecord
    validates :book_title, :author, presence: true
    belongs_to :user
    attribute :user_id, default: 0
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
  before_action :set_library, only: %i[ show edit update destroy ]


  

  # GET /libraries or /libraries.json
  def index
    # ransack configuration
    @q = Library.ransack(params[:q])
    @libraries = @q.result(distinct: true)

    # @libraries = Library.all
    if user_signed_in?
      @user = User.find_by(id: current_user.id)
    else
      @user = false
    end
  end

  # GET /libraries/1 or /libraries/1.json
  def show
  end

  # GET /libraries/new
  def new
    @library = Library.new
  end

  #Get /libraries/1
  def edit
  end


  def search
    if library_params[:search].blank?
      redirect_to root_path and return
    else
      @parameter = library_params[:search].downcase
      # results = Coffeeshop. all.where ("lower (name) LIKE ?" "%#{@parameter}%")
      # @results = Coffee.joins(:reviews, :coffeeshops) .search (params [:search])
      @books = Library.where("lower(book_title) LIKE ?", "%#{@parameter}%" )
      @users = User.all.where("lower(name) LIKE ?", "%#{@parameter}%" )
      puts 'hiiiii'
      puts @books
      redirect_to libraries_search_path
    end
  end

  # POST /libraries or /libraries.json
  def create
    @library = Library.new(book_title: library_params[:book_title], author: library_params[:author], publish_year: 
    library_params[:publish_year], user_id: current_user.id)

    respond_to do |format|
      if @library.save
        format.html { redirect_to libraries_path, notice: "Library was successfully created." }
        format.json { render :show, status: :created, location: @library }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libraries/1 or /libraries/1.json
  def update
    respond_to do |format|
      if @library.update(library_params)
        format.html { redirect_to libraries_path, notice: "Library was successfully updated." }
        format.json { render :show, status: :ok, location: @library }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @library.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libraries/1 or /libraries/1.json
  def destroy
    require 'pry'
    binding.pry
    @library.destroy
    respond_to do |format|
      format.html { redirect_to libraries_url, notice: "Library was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # Post borrow_book/1 to borrow or check if you can borrow book
  def borrow
    @library = Library.find_by!(id: params[:id]) 
    Waitinglist.create(user_id: params[:id], library_id: params[:id]).save
    respond_to do |format|
      format.html { redirect_to waitinglists_path, notice: "You have been added to the waiting lists succsfully for that book." }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_library
      @library = Library.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    # def library_params
    #   params.require(:library).permit(:id, :book_title, :author, :publish_year, :user_id, :search)
    # end
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/views/libraries/_form.html.erb
<%= form_with(model: library) do |form| %>
  <% if library.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(library.errors.count, "error") %> prohibited this library from being saved:</h2>

      <ul>
        <% library.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :book_title %>
    <%= form.text_area :book_title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_area :author %>
  </div>

  <div class="field">
    <%= form.label :publish_year %>
    <%= form.number_field :publish_year %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/libraries/_search_forms.html.erb
<%= search_form_for @q do |f| %>

  <%= f.search_field :book_title_cont %>

  <%= f.submit %>
<% end %>

app/views/libraries/edit.html.erb
<h1>Editing Library</h1>

<%= render 'form', library: @library %>

<%= link_to 'Show', @library %> |
<%= link_to 'Back', libraries_path %>

app/views/libraries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Libraries</h1>

<%= render 'search_forms.html.erb' %>

<table>
  <thead>
    <tr>
      <th>Book title</th>
      <th></th>
      <th>Author</th>
      <th></th>
      <th>Publish year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @libraries.each do |library| %>
      <tr>
        <td><%= library.book_title %></td>
        <td></td>
        <td><%= library.author %></td>
        <td></td>
        <td><%= library.publish_year %></td>

        <% if user_signed_in? == true %>
          <td><%= link_to 'Borrow', borrow_book_path(library.id), :params => {user_id: current_user.id}, method: :post %></td>

          <% if current_user.admin == 'true'|| current_user.librarian == 'true' %>
            <td><%= link_to 'Edit', edit_library_path(library) %></td>
            <td><%= link_to 'Destroy', library_delete_path(library), method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
        <% end %>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/libraries/new.html.erb
<h1>New Library</h1>

<%= render 'form', library: @library %>

<%= link_to 'Back', libraries_path %>

app/views/libraries/search.html.erb
<h3>Search Results:</h3>
<% @books.each do |book|%>
<%= link_to book.book_title, show_book_path(book.id) %>
<% end %>
<hr>

<% @users.each do |user| %>
<%= link_to user.name, user_path(user.id) %>
<% end %>

app/views/libraries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Book title:</strong>
  <%= @library.book_title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @library.author %>
</p>

<p>
  <strong>Publish year:</strong>
  <%= @library.publish_year %>
</p>

<%= link_to 'Edit', edit_library_path(@library) %> |
<%= link_to 'Back', libraries_path %>