config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  

  # libraries
  root 'libraries#index'
  
  get '/Libraries', to: 'libraries#index', as: 'libraries'
  post '/Libraries', to: 'libraries#create', as: 'add_book'
  delete '/Libraries/:id', to: 'libraries#destroy', as: 'library_delete'
  get '/Libraries/new', to: 'libraries#new', as: 'new_library'
  patch '/libraries/:id', to: 'libraries#update'
  post '/libraries/:id/borrow', to: 'libraries#borrow', as: 'borrow_book'
  get '/libraries/:id', to: 'libraries#show', as: "show_book"
  get '/libraries/:id/edit', to: 'libraries#edit', as: 'edit_library'

  # users

  get '/users', to: 'users#index', as: 'users'
  post '/users', to: 'users#create'
  get '/users/signin', to: 'users#signin', as: 'signin'
  post '/users/login', to: 'users#login', as: 'login'
  get '/users/new', to: 'users#new', as: 'new_user'
  get '/users/:id', to: 'users#edit', as: 'user'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update'
  put '/users/:id', to: 'users#update'
  delete '/users/:id', to: 'users#destroy'

  get '/waitinglist', to: 'waitinglists#index', as: 'waitinglists'
  post '/waitinglist/:id', to: 'waitinglists#new'
end

app/models/waitinglist.rb
class Waitinglist < ApplicationRecord
  has_many :users
  has_many :libraries
end

app/controllers/waitinglists_controller.rb
class WaitinglistsController < ApplicationController
  

  # GET /waitinglists or /waitinglists.json
  def index
    @waitinglists = Waitinglist.all
  end

  # GET /waitinglists/1 or /waitinglists/1.json
  def show
  end

  # GET /waitinglists/new
  def new
    @waitinglist = Waitinglist.new
  end

  # GET /waitinglists/1/edit
  def edit
  end

  # POST /waitinglists or /waitinglists.json
  def create
    @waitinglist = Waitinglist.new(waitinglist_params)

    respond_to do |format|
      if @waitinglist.save
        format.html { redirect_to @waitinglist, notice: "Waitinglist was successfully created." }
        format.json { render :show, status: :created, location: @waitinglist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @waitinglist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /waitinglists/1 or /waitinglists/1.json
  def update
    respond_to do |format|
      if @waitinglist.update(waitinglist_params)
        format.html { redirect_to @waitinglist, notice: "Waitinglist was successfully updated." }
        format.json { render :show, status: :ok, location: @waitinglist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @waitinglist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waitinglists/1 or /waitinglists/1.json
  def destroy
    @waitinglist.destroy
    respond_to do |format|
      format.html { redirect_to waitinglists_url, notice: "Waitinglist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_waitinglist
      @waitinglist = Waitinglist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def waitinglist_params
      params.require(:waitinglist).permit(:user_id, :library_id)
    end
end

app/helpers/waitinglists_helper.rb
module WaitinglistsHelper
end

app/views/waitinglists/_form.html.erb
<%= form_with(model: waitinglist) do |form| %>
  <% if waitinglist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(waitinglist.errors.count, "error") %> prohibited this waitinglist from being saved:</h2>

      <ul>
        <% waitinglist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :library_id %>
    <%= form.text_field :library_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/waitinglists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Waitinglists</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th></th>
      <th></th>
      <th>Book</th>
      <th colspan="10"></th>
    </tr>
  </thead>

  <tbody>
    <% @waitinglists.each do |waitinglist| %>
      <% puts 'here' %>
      <% puts waitinglist.library_id %>
      <% puts  waitinglist.user_id %>
      <tr>
        <td><%= User.find_by(id: waitinglist.user_id).name  %></td>
        <td></td>
        <td></td>
        <td><%= Library.find_by(id: waitinglist.library_id).book_title %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/waitinglists/new.html.erb
<h1>New Waitinglist</h1>

<%= render 'form', waitinglist: @waitinglist %>

<%= link_to 'Back', waitinglists_path %>

app/views/waitinglists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Library:</strong>
  <%= Library.find_by(id: @waitinglist.library_id).book_title %>
</p>

<p>
  <strong>User:</strong>
  <%= User.find_by(id: @waitinglist.user_id).name %>
</p>

<%= link_to 'Edit', edit_waitinglist_path(@waitinglist) %> |
<%= link_to 'Back', waitinglists_path %>