config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  

  # libraries
  root 'libraries#index'
  
  get '/Libraries', to: 'libraries#index', as: 'libraries'
  post '/Libraries', to: 'libraries#create', as: 'add_book'
  delete '/Libraries/:id', to: 'libraries#destroy', as: 'library_delete'
  get '/Libraries/new', to: 'libraries#new', as: 'new_library'
  patch '/libraries/:id', to: 'libraries#update'
  post '/libraries/:id/borrow', to: 'libraries#borrow', as: 'borrow_book'
  get '/libraries/:id', to: 'libraries#show', as: "show_book"
  get '/libraries/:id/edit', to: 'libraries#edit', as: 'edit_library'

  # users

  get '/users', to: 'users#index', as: 'users'
  post '/users', to: 'users#create'
  get '/users/signin', to: 'users#signin', as: 'signin'
  post '/users/login', to: 'users#login', as: 'login'
  get '/users/new', to: 'users#new', as: 'new_user'
  get '/users/:id', to: 'users#edit', as: 'user'
  get '/users/:id/edit', to: 'users#edit', as: 'edit_user'
  patch '/users/:id', to: 'users#update'
  put '/users/:id', to: 'users#update'
  delete '/users/:id', to: 'users#destroy'

  get '/waitinglist', to: 'waitinglists#index', as: 'waitinglists'
  post '/waitinglist/:id', to: 'waitinglists#new'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SecurityLibraryAppKelvinEdward</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href='/'>Home</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">

          <% if user_signed_in? %>
            <li class="nav-item">
              <%= link_to 'Logout', destroy_user_session_path(current_user.id), method: :delete, data: { confirm: 'Are you sure?' }, style: 'color:white; margin:20px; margin-top:20px;'%>
            </li>
          <% else %>
              <li class="nav-item">
                <%= link_to 'Signin',  new_user_session_path, style: 'color:white; margin:20px; margin-top:20px;'%>
              </li>
          <% end %>
          
          <% if user_signed_in? == true %>
            <% if current_user.admin == 'true' || current_user.librarian == 'true' %>
              <li class="nav-item">
                  <%= link_to 'Manage Books', libraries_path, style: 'color:white; margin:20px; margin-top:20px;'%>
              </li>
              <li class="nav-item">
                  <%= link_to 'Add Book', new_library_path, style: 'color:white; margin:20px; margin-top:20px;'%>
              </li>
            <% else %>
              <li class="nav-item">
                <%= link_to 'Books Available', libraries_path, style: 'color:white; margin:20px; margin-top:20px;'%>
              </li>
            <% end %>
          <% else %>
            <li class="nav-item">
              <%= link_to 'Books Available', libraries_path, style: 'color:white; margin:20px; margin-top:20px;'%>
            </li>
          <% end %>
          
          <% if user_signed_in? == true %>
            <% if current_user.admin == 'true' %>
            <li class="nav-item">
                <%= link_to 'Manage Users', users_path, style: 'color:white; margin:20px; margin-top:20px;'%>
            </li>
            <% end %>
          <% end %>

          <% if user_signed_in? == true %>
            <li class="nav-item">
  
                <%= link_to 'Waiting List', waitinglists_path, style: 'color:white; margin:20px; margin-top:20px;'%>
            
            </li>
          <% end %>
        </ul>

      </div>
    </div>
  </nav>


  
      <div class = 'container-fluid'>
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>
      <div class = 'container-fluid'>
    </body>
  
</html>